name: maritime_env
channels:
  - conda-forge
  - defaults

dependencies:
  # ---------- Python Version ----------
  # Change this to 3.10 or 3.11 if packages are not compatible with 3.12
  - python=3.12

  # ---------- Core scientific and data libraries ----------
  - numpy>=1.23.0
  - pandas>=1.5.0
  - scipy>=1.9.0
  - scikit-learn>=1.2.0

  # ---------- Visualization ----------
  - matplotlib>=3.6.0
  - seaborn>=0.12.0

  # ---------- GPU & Deep Learning Frameworks ----------
  # CUDA toolkit for GPU acceleration (version 11.8 as an example)
  - cudatoolkit=11.8
  
  # PyTorch (GPU-compatible build)
  - pytorch>=2.0.0

  # ---------- Miscellaneous Helpful Tools ----------
  - tqdm>=4.64.0
  - sentencepiece>=0.1.97
  - tokenizers>=0.13.2
  - requests>=2.28.0
  - protobuf>=3.20.0
  - datasets>=3.2.0

  # We'll install some packages via pip. We need pip in the environment.
  - pip

  # ---------- Pip-only packages ----------
  - pip:
      # Hugging Face Transformers (BERT, GPT, etc.)
      - transformers>=4.28.0
      # Google BERT library (if you need it)
      - bert>=2.2.0
      - tensorflow>=2.12.0
      - tf_keras>=2.18.0
      - accelerate>=0.26.0
