name: maritime_env
channels:
  - conda-forge
  - defaults
dependencies:
  # Choose Python 3.12; if that doesn't work well, consider Python 3.10 or 3.11
  - python=3.12

  # ---------- Core scientific and data libraries ----------
  - numpy>=1.23.0
  - pandas>=1.5.0
  - scipy>=1.9.0
  - scikit-learn>=1.2.0

  # ---------- Visualization ----------
  - matplotlib>=3.6.0
  - seaborn>=0.12.0

  # ---------- Miscellaneous ----------
  - tqdm>=4.64.0
  - sentencepiece>=0.1.97
  - tokenizers>=0.13.2
  - requests>=2.28.0
  - protobuf>=3.20.0

  # We need 'pip' in order to install packages listed under pip:
  - pip

  # ---------- Pip-only packages ----------
  - pip:
      - transformers>=4.28.0
      - bert>=2.2.0
